### ISSUE TITLE
Option to hide menu bar icon

### ISSUE THREAD

**Issue by inverseTrig** [artginzburg/MiddleClick-BigSur#40]
With the new MacBook having a notch, the amount of icons we can have displayed has been significantly limited. It would be nice to have an option to disable the icon from being displayed in the menu bar.

**Comment by salazarbarrera** [comment]
I came to suggest the exact same thing, but while I just noticed it is sort of implemented already. If you grab the icon while holding the command key, you can drag it outside the bar, effectively removing it. The program will still run in the background. In order to restore it, you need to re-open the app in the launchpad or dock.
